language: php

php:
  - 5.3.9
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev install
